# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "6161a861876ab43d7e3d46e0afeb2322"
name = "agora-x"
handle = "agora-x"
application_url = "https://attendance-folks-hits-generates.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "agorax-app.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://attendance-folks-hits-generates.trycloudflare.com/auth/callback",
  "https://attendance-folks-hits-generates.trycloudflare.com/auth/shopify/callback",
  "https://attendance-folks-hits-generates.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
